### ISSUE TITLE
Mrinal Chaudhari

### ISSUE THREAD

**Issue by MrinalChaudhari** [hil-se/fds#10]
Hello,

I am from Pune, India. I have a degree in Information technology. I intern in GTT company where I used to work as a developer. I had two years of experience in Tata Consultancy Services as Database Administrator. I always fascinating about data and how data is handle in today's era. Because Data science is comes from various background such as statistic, applied mathematics and many more. And I would love to explore further more in this area. I am glad that I am part of this class and very excited to know more about you all.

**Comment by azhe825** [comment]
Hello @MrinalChaudhari, welcome to RIT!
