### ISSUE TITLE
Assignment 1 , module not found

### ISSUE THREAD

**Issue by ys2688** [hil-se/fds#104]
when I run the A1 file my pycharm says module sklearn is not found . I have installed the package . so what would be the bets way to resolve this 
<img width="1470" alt="Screen Shot 2022-08-29 at 10 13 47 AM" src="https://user-images.githubusercontent.com/111996882/187221936-495f4b9f-a2fc-438e-bb12-31ada3612254.png">

**Comment by azhe825** [comment]
Have you tried using a terminal to run it? 
```
python A1.py
```

**Comment by ys2688** [comment]
so after installing scikit-learn multiple times i was able to run the code  in a different project. I was not able to run the A1.py file in my pycharm , I created a new project and did the code  , also i was not able to load the data source . so i downloaded Iris_train and Iris_test seperately and loaded them manually and was able to get the output.

**Comment by djpnce** [comment]
Hi Professor,

My name is Dave Putz. I am no longer in this class, so please kindly remove me from email comms.



Thanks!

**Comment by azhe825** [comment]
@djpnce you can unwatch this repo. These emails are pushed by GitHub.
