### ISSUE TITLE
Correction for Assignment 2

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#106]
Do not consider '?' as missing values when implementing my_NB.py.

Treat that as one of the possible values X can take. 

This should make Assignment 2 easier and last time I checked, sklearn.naive_bayes.CategoricalNB also does not consider missing values.

**Comment by rohaan2614** [comment]
The "?" does not provide useful information about the features. Wouldn't this introduce an error into the model?

**Comment by azhe825** [comment]
@rohaan2614 
You are right. “?” Should be treated as missing values in this dataset. However, this assignment tries to match the categorical naive bayes classifier on sklearn, which does not have a missing value handling mechanism.

**Comment by rohaan2614** [comment]
Can we remove the rows that contain "?" before calculating the
probabilities? Also, I noticed there are only 200 records (including "?"
rows). Is this sufficient for reliable probabilities?

**Comment by azhe825** [comment]
@rohaan2614 
No. The goal of this assignment is not to predict as accurate as you can. But to implement the naive bayes classifier. Do not modify the A2.py file.
