### ISSUE TITLE
Shrunali Paygude

### ISSUE THREAD

**Issue by ShrunaliPaygude** [hil-se/fds#11]
Hello everyone,
I am from Pune, India.
The COVID situation had made my plan for masters a bit dicey but learning Data Science was something that I always wanted to pursue.

I did my undergrad in Electronics and Telecommunication, so learning the foundations of data science, which is very new for me, will prove crucial in my journey.

Hope to see you all in Spring! Till then, happy learning :)

**Comment by azhe825** [comment]
@ShrunaliPaygude welcome to RIT! Happy Learning!
