### ISSUE TITLE
Assignment 10: Decision Boundary Formatting for List of Floats 

### ISSUE THREAD

**Issue by thapa-jeevan** [hil-se/fds#115]
For Assignment 10, the decision boundary for `min_impurity_decrease` has integer for the start value ("min_impurity_decrease": [0, 0.1]) in [A10.py line 30](https://github.com/hil-se/fds/blob/33793a49cffc8898b2dd51ddf29fe751b7ac7691/assignments/Tuning/A10.py#L30C101-L30C101). Since the [data type of list elements](https://github.com/hil-se/fds/blob/33793a49cffc8898b2dd51ddf29fe751b7ac7691/assignments/Tuning/my_GA_hint.py#L231C1-L232C1) is determined by the first element, this setup could pose a problem. If the boundary is configured similarly (with starting integer starting value) in the assignment evaluation pipeline, all sampled values will be rounded off. This might not be desirable for float boundaries.

**Comment by azhe825** [comment]
Good point. I have updated A10.py file to make it [0.0, 0.1]. The actual grading files do not have such problem.

**Comment by thapa-jeevan** [comment]
Thank you! Closing the issue.
