### ISSUE TITLE
Path incorrect for `my_evaluation`

### ISSUE THREAD

**Issue by bipin-lekhak** [hil-se/fds#116]
Running `test.py` for project returns an error:
`ModuleNotFoundError: No module named 'assignments.assignment8'`

This is being caused because of [this line](https://github.com/hil-se/fds/blob/f48bc35ca8fbe6caf1f559b6c1d4196e5144bd15/assignments/project/test.py#L8C1-L8C1):

`from assignments.assignment8.my_evaluation import my_evaluation`

This should be solved with:

`from assignments.Evaluation.my_evaluation import my_evaluation`

This is because of the project structure.

**Comment by azhe825** [comment]
Yes. That was a mistake. I have updated the [test.py](https://github.com/hil-se/fds/blob/master/assignments/project/test.py) file to correct the path. Please pull from this repo or make the correction yourself.
