### ISSUE TITLE
Hey, I am Vinayak Sengupta

### ISSUE THREAD

**Issue by vinzlercodes** [hil-se/fds#12]
Hi everyone,
I am from Mumbai, India.

The COVID-19 situation, like for most people here had made my plan for masters quite uncertain as well, but a career in the field of Data Science was something that I always planned on pursuing.

I did my undergrad studies in Computer Science and Engineering, so learning the foundations of data science, are relatively familiar for me, but I believe I have a long journey ahead of me yet.

Hope to connect with you all and meet up in Spring! Till then, All the best and Cheers!

**Comment by azhe825** [comment]
All the best and Cheers!
