### ISSUE TITLE
Hello, I'm Neha.

### ISSUE THREAD

**Issue by neha6351** [hil-se/fds#13]
Hello everyone,

I am Neha, currently residing in Patna, India.
I was captivated by how much sense it makes when data is analyzed and processed effectively. I cannot think of any sector which cannot be favored by Data Science. I am looking forward for all the amazing years here at RIT.

I am not an exception when it comes to COVID crisis. 
Hope we get a vaccine soon for COVID-19! See you all soon!

**Comment by azhe825** [comment]
Welcome to RIT! See you soon @neha6351!
