### ISSUE TITLE
Hello, I am Yash

### ISSUE THREAD

**Issue by YashBangera7** [hil-se/fds#14]
Hey there. I am Yash Mahesh Bangera. I hope you guys are doing well. I am currently in Mumbai, India, and am affected badly by the Corona pandemic. Everything here is shut and under lockdown.  I am, however, keen on learning new things each day and look forward to this course too. My goal after graduation is to be able to introduce solutions that make use of Data Science, Machine Learning, and Artificial Intelligence that could help the community as much as possible.

**Comment by azhe825** [comment]
Welcome, @YashBangera7! Good luck with your study!
