### ISSUE TITLE
Hello, I'm Rochelle

### ISSUE THREAD

**Issue by RochelleAllan** [hil-se/fds#15]
Hi everyone,
I'm Rochelle and I am currently in Bangalore, India. 
This Pandemic has been challenging to say the least and Im really hoping I get to meet you all in person in Spring 2021!
I wanted to dive into Data Science because there is so much that can be learnt from Data and can be used in every field.

Can't wait to learn and meet you all soon !

**Comment by azhe825** [comment]
Welcome to RIT, @RochelleAllan! Hope everything gets well in Bangalore.
