### ISSUE TITLE
Abdullah Alsaleh

### ISSUE THREAD

**Issue by AbdullahA93** [hil-se/fds#16]
Hello everyone,
This is Abdullah Alsaleh from Saudi Arabia, currently in Rochester, NY.
I have a bachelor's degree in information technology, and my main areas of interest are Data applications and Web development. Back in Saudi Arabia, I have worked as a web developer and system administrator in the Education sector for almost 3 years.
Over the years, my passion for gaining experience, enhancing my skills, and expanding my knowledge in data and analytics of a bigdata have evolved. I always believe in data science as one of the most important success factors in all fields.

I'm very excited about this course! With all that is going on with the Coronavirus, I hope we enjoy the course together and hope to see you soon in the spring...

**Comment by azhe825** [comment]
Welcome, @AbdullahA93! Good to know that you have made it to Rochester.
