### ISSUE TITLE
"Questions About the Course" task requires a reply

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#17]
Hello,

In myCourses, the "Getting Started -> Questions About the Course" task requires a "reply" in order to mark the task as completed. However, the specific instruction, in the task's description, is to not reply to the task. Please advise.

Thank you

**Comment by azhe825** [comment]
@rigved Thanks for pointing that out.
Now it is a manual task. Please check.

**Comment by rigved** [comment]
Works great now!
