### ISSUE TITLE
Hello, I'm Chenliang

### ISSUE THREAD

**Issue by fantasia1314** [hil-se/fds#18]
Hello, My name is Chenliang Cao, but you can call me George. I'm from Shanghai, China. but I stayed in Rochester after graduating from U of R two years ago. I have a degree of Applied mathematics and I am very new to this data science area. 
I'm excited about this course, and hopefully everything can get back on track from this COVID-19 situation.

**Comment by azhe825** [comment]
Welcome to RIT, @fantasia1314!
