### ISSUE TITLE
Hello everyone, I'm Sultan

### ISSUE THREAD

**Issue by salmassari** [hil-se/fds#20]
Hi everyone!!

I'm Sultan Almassari, a Software Engineering student, currently in Rochester. As an experience, I used to work as Quality Assurance engineer for 3 years.

The reason why I opt to be educated in Data science is that it will give me a sound knowledge of how to implement its application with my interest. This will give me an opportunity to integrate several fields(e.g. data science with QA) to come up with a good mined and predictable data. So, I am so excited to know the recipe and the secret of data science!

I believe that no one is happy with this pandemic, but we need to adapt ourselves. Anyway, looking forward to knowing all of you guys!

**Comment by azhe825** [comment]
Hi @salmassari, welcome to RIT! Hope this course will be the start of your journey into data science.
