### ISSUE TITLE
Nishant Nair

### ISSUE THREAD

**Issue by nairnish** [hil-se/fds#21]
Hello everyone,

Hope you're doing well and keeping safe during this pandemic.

I am Nishant Nair and I'm from India. I have been working in the field of data and analytics for over 5 years now and have undertaken various roles during this stint which includes data analyst, business analyst, business intelligence engineer and decision scientist to name a few. I wanted to dig much deeper into data science in the space of statistical methods, optimisation techniques, visualisation and automation. My journey in the field of analytics and prevalent interest in the "Science" of data, naturally led me to take up MS in Data Science at RIT. Additionally, with the flexibility that RIT offers and wide variety of courses that one can choose from, really puts it above all for me, personally.

Apart from work, I also like to indulge myself in doing some regular exercises and yoga just to manage day-to-day physical or mental  workload. I like to listen to a lot of songs and keep exploring new artists on the go. I would like to believe that I have a good taste in them, so if you're looking for some recommendations, please feel free to reach out.

Hope to see you soon in person, by Spring. I am positive that the current situation will turnaround !! Let's plan to grow and develop together both professionally and personally.

Thanks and best regards

**Comment by azhe825** [comment]
Welcome to RIT, @nairnish!
