### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by dsimran** [hil-se/fds#23]
Hello everyone, my name is Simran Deshmukh and I am from Mumbai,India. I have completed my B.E in computer and was hired by Accenture as an ASE after my undergraduation. I have also completed an internship with Robokart. Well, the situation of COVID-19 in my locality is pretty much under control however,we are still under lockdown for safety purpose. I am also very excited to start with this course as it will help me learn new skills and concepts so as to become a good data scientist after my graduation.

**Comment by azhe825** [comment]
Welcome to RIT, @dsimran! Good luck with your study!
