### ISSUE TITLE
Hi! I'm Yuvraj

### ISSUE THREAD

**Issue by Y-Singh** [hil-se/fds#24]
Hello everyone,

I'm Yuvraj Singh. I'm currently staying in Rochester. Unfortuntely, because of COVID, I'm tied down with either work or school since there isn't much anyone can do right now. I just started my BS/MS in Computer Science and I plan to specialize in Big Data and Data Management.  I want to learn more about how to handle large sets of data and what one can learn from it.

**Comment by azhe825** [comment]
Welcome, @Y-Singh! It is now a good time to enjoy the beautiful nature side of Rochester.
