### ISSUE TITLE
It is now required to change your DSCI-633 repo to private

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#26]
As many students have suggested, it is better to keep the DSCI-633 repos private and only accessible by the instructor and the TA. 

Keeping repos have the following advantages:
1. Others cannot see your work until you decide to make it public.
2. Cheating would become much more difficult.
3. Now private repos can be created by free GitHub accounts so why not?

If you have already created a public repo, I will be demonstrating on Aug 25 for how to change it to private.

If you have not created a repo yet, follow the new version of Assignment 1 to create a private repo.

Now everyone needs to also invite the instructor and the TA (Github ID: azhe825, ketakisbarde) as collaborators to their private repos.

**Comment by dsimran** [comment]
Hello,
Since I have created the repo as public for the first assignment ,will wait
for your instructions for changing those to private.In that case,should I
only add assignment 1folder to the public repo?

**Comment by azhe825** [comment]
Either way is good. You can copy either only assignment 1 or all the assignments for now.

However, you will need to update the corresponding assignment each time a new assignment is released (since we might change the assignment code before releasing). I will talk more about that on Tursday.

**Comment by dsimran** [comment]
Ok,thank you.Will get back to you incase I have any further questions.
