### ISSUE TITLE
Entropy can be larger than 1

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#27]
Entropy score can be larger than 1 when more than 2 classes are presented.
For three classes, if each class has the same number of samples, entropy = 1.58

**Comment by neha6351** [comment]
Hello Professor,

I have calculated the gini and entropy so far. I understand how
find_best_split function is going to work theoretically, but I am stuck as
my python is weak. I would need some help to realize the theory into python
codes, what would you suggest that could help me with this?

Regards,
Neha Kumari
FDS student

**Comment by azhe825** [comment]
You can search online for pseudo-codes implementing decision trees. It should help you better understand what the actual code should look like.

**Comment by vinzlercodes** [comment]
Dear Sir,

Do we need to implement the Tree according to how the functions and classes
have been pre-defined in the original file? Or we can create it fresh on
our own from scratch?

**Comment by azhe825** [comment]
You can do it from scratch (by completing the my_DT.py code where only the interface has been defined). If you find that to be too challenging, then you can rely on the my_DT_hint.py code (you can also modify that code or just fill-in the blanks).
