### ISSUE TITLE
Question about grading policy for assignment 2

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#29]
Hello Prof. Zhe,

Is the grading policy for assignment 2 based on the number of same probability predictions from the `predict_proba` method as well? I'm asking because I have implemented Hunt's algorithm from the slides with the assumption that each feature will be evaluated on only one node. Once a feature is selected as the decision condition for a node, subsequent nodes will only use one of the remaining features to make a decision. This assumption leads to a more generalized decision tree than the one calculated by sklearn. For more context, here are the two trees, one from my program and the second from sklearn:

```python
[['PetalLengthCm', 3.0, 'l', 'Iris-setosa'], ['PetalWidthCm', 1.8, 'l', 'Iris-versicolor'], ['SepalLengthCm', 6.0, 'ge', 'Iris-virginica'], ['SepalWidthCm', 3.2, 'l', 'Iris-virginica']]
```
```python
|--- feature_2 <= 2.45
|   |--- class: Iris-setosa
|--- feature_2 >  2.45
|   |--- feature_3 <= 1.75
|   |   |--- feature_2 <= 4.95
|   |   |   |--- feature_3 <= 1.65
|   |   |   |   |--- class: Iris-versicolor
|   |   |   |--- feature_3 >  1.65
|   |   |   |   |--- class: Iris-virginica
|   |   |--- feature_2 >  4.95
|   |   |   |--- feature_3 <= 1.55
|   |   |   |   |--- class: Iris-virginica
|   |   |   |--- feature_3 >  1.55
|   |   |   |   |--- feature_2 <= 5.45
|   |   |   |   |   |--- class: Iris-versicolor
|   |   |   |   |--- feature_2 >  5.45
|   |   |   |   |   |--- class: Iris-virginica
|   |--- feature_3 >  1.75
|   |   |--- feature_2 <= 4.85
|   |   |   |--- feature_1 <= 3.10
|   |   |   |   |--- class: Iris-virginica
|   |   |   |--- feature_1 >  3.10
|   |   |   |   |--- class: Iris-versicolor
|   |   |--- feature_2 >  4.85
|   |   |   |--- class: Iris-virginica
```
My code makes the same predictions on the given test data, but with a lower confidence, which can be seen when the data from `predict_proba` is printed.

**Comment by azhe825** [comment]
Your code is expected to behave the same as the sklearn version (and as our lectures). If it does not, it is possible that you get a score lower than 7. This has nothing to do with which implementation is better.

**Comment by rigved** [comment]
Thank you for the clarification Prof. Zhe. I went ahead and implemented the hint file one for now because it provides the same prediction probabilities as the one from `sklearn`.
