### ISSUE TITLE
Question about Assignment 2

### ISSUE THREAD

**Issue by YashBangera7** [hil-se/fds#30]
Sir, I have written this code : 
def find_best_split(self, pop, X, labels):
        # Find the best split
        # Inputs:
        #   pop:    indices of data in the node
        #   X:      independent variables of training data
        #   labels: dependent variables of training data
        # Output: tuple(best feature to split, weighted impurity score of best split, splitting point of the feature, [indices of data in left node, indices of data in right node], [weighted impurity score of left node, weighted impurity score of right node])
        ######################
        best_feature = None
        cans_arr = []
        df_below_threshold = []
        df_above_threshold = []
        df_per_midpoint = []
        labels_below_threshold = []
        labels_above_threshold = []
        midpoints = []
        impurity_values = []
        impurity_values_b = []
        impurity_values_a = []
        for feature in X.keys():
            cans = np.array(X[feature][pop])
            cans_arr.append(cans)
        first_switch = np.where(labels[:-1] != labels[1:])[0][0]         
        for i in range(0,len(cans_arr),1):
            mid_value = ((cans_arr[i][first_switch] + cans_arr[i][first_switch+1])/2)
            midpoints.append(mid_value)
        for i in range(0,len(midpoints),1):  
            df_below_threshold.append(X.loc[X[X.keys()[i]]<=midpoints[i]])
            df_above_threshold.append(X.loc[X[X.keys()[i]]>midpoints[i]])
            df_per_midpoint.append([df_below_threshold,df_above_threshold])
            labels_below_threshold.append((labels[X[X.keys()[i]]<=midpoints[i]]))
            labels_above_threshold.append((labels[X[X.keys()[i]]>midpoints[i]]))

( Just the starting portion of the code)
But, I am getting this error in python. I do not understand why this is so. I get it when I use clf.fit(X,y) :
IndexError                                Traceback (most recent call last)
<ipython-input-58-afd4cda53619> in <module>
----> 1 clf.fit(X,y)

~\DSCI-633\assignments\assignment2\my_DT_hint.py in fit(self, X, y)
    168                 else:
    169                     # Find the best split using find_best_split function
--> 170                     best_feature = self.find_best_split(current_pop, X, labels)
    171                     if (current_impure - best_feature[1]) > self.min_impurity_decrease * N:
    172                         # Split the node

~\DSCI-633\assignments\assignment2\my_DT_hint.py in find_best_split(self, pop, X, labels)
     75         first_switch = np.where(labels[:-1] != labels[1:])[0][0]
     76         for i in range(0,len(cans_arr),1):
---> 77             mid_value = ((cans_arr[i])[first_switch] + (cans_arr[i])[first_switch+1])/2
     78             midpoints.append(mid_value)
     79         for i in range(0,len(midpoints),1):

IndexError: index 44 is out of bounds for axis 0 with size 39

**Comment by azhe825** [comment]
It is hard to know what your code does with no indent. Use ‘’’ for codes.

**Comment by YashBangera7** [comment]
def find_best_split(self, pop, X, labels):
        # Find the best split
        # Inputs:
        #   pop:    indices of data in the node
        #   X:      independent variables of training data
        #   labels: dependent variables of training data
        # Output: tuple(best feature to split, weighted impurity score of best split, splitting point of the feature, [indices of data in left node, indices of data in right node], [weighted impurity score of left node, weighted impurity score of right node])
        ######################
        best_feature = None
        cans_arr = []
        for feature in X.keys():
            cans_arr.append(np.array(X[feature][pop]))
        first_switch = np.where(labels[:-1] != labels[1:])[0][0] 
        df_below_threshold = []
        df_above_threshold = []
        df_per_midpoint = []
        labels_below_threshold = []
        labels_above_threshold = []
        midpoints = []
        impurity_values = []
        impurity_values_b = []
        impurity_values_a = []
        for a in range(0,len(cans_arr),1):
            midpoints.append((cans_arr[a][first_switch] + cans_arr[a][first_switch+1])/2)
        for i in range(0,len(midpoints),1):  
            df_below_threshold.append(X.loc[X[X.keys()[i]]<=midpoints[i]])
            df_above_threshold.append(X.loc[X[X.keys()[i]]>midpoints[i]])
            df_per_midpoint.append([df_below_threshold,df_above_threshold])
            labels_below_threshold.append((labels[X[X.keys()[i]]<=midpoints[i]]))
            labels_above_threshold.append((labels[X[X.keys()[i]]>midpoints[i]]))
        for j in range(0,len(labels_below_threshold),1):
            impurity_values_b.append(self.impurity(labels_below_threshold[j]))
        for k in range(0,len(labels_above_threshold),1):
            impurity_values_a.append(self.impurity(labels_above_threshold[j]))
        info_gain_per_feature = []  
        information_node_arr_a = []
        information_node_arr_b = []
        for l in range(0,len(labels_below_threshold),1):
            current_labels_b = labels_below_threshold[l]
            current_labels_a = labels_above_threshold[l]
            labels_b_len = len(current_labels_b)
            labels_a_len = len(current_labels_a)
            unique_current_b = pd.Series(labels_below_threshold[l]).unique()
            unique_current_a = pd.Series(labels_above_threshold[l]).unique()
            value_counts_b = pd.Series(labels_below_threshold[l]).value_counts()
            value_counts_a = pd.Series(labels_above_threshold[l]).value_counts()
            if self.criterion=="entropy":
                sum_log_prob_b = 0
                sum_log_prob_a = 0
                for m in range(0,len(unique_current_b),1):
                    sum_log_prob_b = sum_log_prob_b + (value_counts_b[m]/labels_b_len)(np.log2(value_counts_b[m]/labels_b_len))
                for n in range(0,len(unique_current_a),1): 
                    sum_log_prob_a = sum_log_prob_a + (value_counts_a[n]/labels_a_len)(np.log2(value_counts_a[n]/labels_a_len))
                info_node_a = (labels_b_len/(labels_a_len+labels_b_len))*(-sum_log_prob_b)
                info_node_b = (labels_a_len/(labels_a_len+labels_b_len))*(-sum_log_prob_a)
                information_node = info_node_a + info_node_b
                information_node_arr_a.append(info_node_a)
                information_node_arr_b.append(info_node_b)
                information_gain = self.impurity(labels)-information_node
                info_gain_per_feature.append(information_gain)
            elif self.criterion=="gini":
                prob_a =0
                prob_b =0
                for m in range(0,len(unique_current_b),1):
                    prob_b = prob_b + (value_counts_b[m]/labels_b_len)*(value_counts_b[m]/labels_b_len)
                for n in range(0,len(unique_current_a),1):    
                    prob_a = prob_a + (value_counts_a[n]/labels_a_len)*(value_counts_a[n]/labels_a_len)
                prob_a_final = 1 - prob_a
                prob_b_final = 1 - prob_b
                info_node_b = (labels_b_len/(labels_a_len+labels_b_len))*(prob_b_final)
                info_node_a = (labels_a_len/(labels_a_len+labels_b_len))*(prob_a_final)
                information_node =  info_node_b + info_node_a
                information_node_arr_b.append(info_node_b)
                information_node_arr_a.append(info_node_a)
                information_gain = self.impurity(labels) - information_node
                info_gain_per_feature.append(information_gain)
        max_information_gain_index = info_gain_per_feature.index(max(info_gain_per_feature))
        best_feature_to_split = X.keys()[max_information_gain_index]
        weighted_impurity_score_best_split = info_gain_per_feature[max_information_gain_index]
        splitting_point_of_feature = midpoints[max_information_gain_index]
        indices_arr = [df_below_threshold[max_information_gain_index].index.values,df_above_threshold[max_information_gain_index].index.values]
        weighted_impurity_score = [information_node_arr_b[max_information_gain_index],information_node_arr_a[max_information_gain_index]]
        best_feature = (best_feature_to_split, weighted_impurity_score_best_split,splitting_point_of_feature,indices_arr,weighted_impurity_score)
        return best_feature

**Comment by YashBangera7** [comment]
def find_best_split(self, pop, X, labels):
        # Find the best split
        # Inputs:
        #   pop:    indices of data in the node
        #   X:      independent variables of training data
        #   labels: dependent variables of training data
        # Output: tuple(best feature to split, weighted impurity score of best split, splitting point of the feature, [indices of data in left node, indices of data in right node], [weighted impurity score of left node, weighted impurity score of right node])
        ######################
        best_feature = None
        cans_arr = []
        for feature in X.keys():
                cans_arr.append(np.array(X[feature][pop]))
        first_switch = np.where(labels[:-1] != labels[1:])[0][0] 
        df_below_threshold = []
        df_above_threshold = []
        df_per_midpoint = []
        labels_below_threshold = []
        labels_above_threshold = []
        midpoints = []
        impurity_values = []
        impurity_values_b = []
        impurity_values_a = []
        for a in range(0,len(cans_arr),1):
                  midpoints.append((cans_arr[a][first_switch] + cans_arr[a][first_switch+1])/2)
        for i in range(0,len(midpoints),1):  
                   df_below_threshold.append(X.loc[X[X.keys()[i]]<=midpoints[i]])
                   df_above_threshold.append(X.loc[X[X.keys()[i]]>midpoints[i]])
                  df_per_midpoint.append([df_below_threshold,df_above_threshold])
                  labels_below_threshold.append((labels[X[X.keys()[i]]<=midpoints[i]]))
                  labels_above_threshold.append((labels[X[X.keys()[i]]>midpoints[i]]

**Comment by YashBangera7** [comment]
![Capture](https://user-images.githubusercontent.com/46867887/92176538-43326700-ee5c-11ea-85e2-7bd16e4b7f18.PNG)

**Comment by YashBangera7** [comment]
I hope its ok now sir

**Comment by YashBangera7** [comment]
![image](https://user-images.githubusercontent.com/46867887/92176601-6a893400-ee5c-11ea-8202-6136dc5b98fe.png)
This is the error trace.

**Comment by YashBangera7** [comment]
No clue why it does this.

**Comment by azhe825** [comment]
I don’t get the idea of your first_switch. It won’t be a correct implementation even if there is no error.

**Comment by YashBangera7** [comment]
Sir, the first switch idea comes from here : https://www.cs.auckland.ac.nz/~pat/706_98/ln/node95.html

**Comment by azhe825** [comment]
It is very different from your implementation:
1. You need to sort by the attribute values
2. Not only the first switch needs to be used, all switches need to be checked

**Comment by YashBangera7** [comment]
Ok sir. I will try implementing that. However, the code that you explained in class gives the same error for me.

**Comment by azhe825** [comment]
I find where your error is. The labels contain all the labels, not only the current node.
So it should be labels[pop] in your first_switch line.

**Comment by YashBangera7** [comment]
Hmm, i understand. I will still try to implement the code with dynamic discretization.

**Comment by azhe825** [comment]
One problem with the dynamic discretization:
What if the feature values before and after the switch point are the same?

**Comment by YashBangera7** [comment]
Hmm, so u suggest I proceed with the normal things as you taught in today's lecture?

**Comment by azhe825** [comment]
No. I am just warning you that you need to handle that problem properly.

**Comment by azhe825** [comment]
Then it will be a more efficient implementation than checking every possible split

**Comment by YashBangera7** [comment]
got it sir. Sir, can u check the below code. I am getting the same error always
![Capture](https://user-images.githubusercontent.com/46867887/92186491-931d2800-ee74-11ea-86e2-3da30137cb8e.PNG)
Here is the trace of the error. 
![image](https://user-images.githubusercontent.com/46867887/92186507-9d3f2680-ee74-11ea-9590-e2bdea4d7fbd.png)

**Comment by azhe825** [comment]
You can debug this error using set_trace:
~~~
from pdb import set_trace
try:
  left_node.append(labels[pop[i]])
except:
  set_trace()
~~~
