### ISSUE TITLE
Assignment 3, do not forget about the smoothing factor self.alpha

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#32]
As stated in the ``__init__()`` function:
```
        # alpha: smoothing factor
        # P(xi = t | y = c) = (N(t,c) + alpha) / (N(c) + n(i)*alpha)
        # where n(i) is the number of available categories (values) of feature i
        # Setting alpha = 1 is called Laplace smoothing
```
Do not forget to use it when calculating P(xi|yj)

**Comment by azhe825** [comment]
And there was a syntax error in the [my_NB_hint.py](https://github.com/hil-se/fds/blob/master/assignments/assignment3/my_NB_hint.py) file (Line 39). Please pull it again or fix it manually.

**Comment by azhe825** [comment]
Check the updated [A3 description](https://github.com/hil-se/fds/blob/master/assignments/assignment3.md) for expected output when running A3.py.

**Comment by azhe825** [comment]
Make sure your implementation considers the following situation:

X[Xi] has two values t, f. but for y==yj, all X[Xi] == t. In this case you should still compute the P(Xi=f|yj) and it won’t be zero because of the smoothing factor alpha.

**Comment by clee25-chwy** [comment]
> Check the updated [A3 description](https://github.com/hil-se/fds/blob/master/assignments/assignment3.md) for expected output when running A3.py.

Hello Professor,

if there is only 60% of the accurate prediction rate when I run my A3.py.
How could I optimize the bad predictions? 

Thanks

**Comment by azhe825** [comment]
@ChunYu-Lee 
First, I would suggest you check if you have the problems discussed above in this issue.
Then, it is always a good idea for students to debug each other's code. This could usually be more efficient than debugging your own code.
