### ISSUE TITLE
Mismatch of the output format of predict_proba() function between sklearn and our implementation

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#36]
There is a mismatch of the output format of predict_proba() function. (I think ours are better.)
So when you what to check the output of the sklearn version of the classifiers, also change the print() function in A#.py.

**Comment by azhe825** [comment]
```
print(preds)
print(probs)
```
would be fine,
otherwise you can 
```
for i,pred in enumerate(predictions):
        print("%s\t%f" % (pred, np.max(probs[i])))
```

**Comment by neha6351** [comment]
Thanks a ton, professor.
