### ISSUE TITLE
Assignment 5 - random state

### ISSUE THREAD

**Issue by YashBangera7** [hil-se/fds#37]
Sir, our fit function doesn't really set the seed of the random state. In this scenario, we get a different output always that is different from the sklearn's default adaBoostClassifier. Is this possible?

**Comment by azhe825** [comment]
It is fine if the output is a bit different due to randomness.

**Comment by YashBangera7** [comment]
Sir, the assignment output is 
![image](https://user-images.githubusercontent.com/46867887/93946238-5e570f00-fd56-11ea-873b-57d35b30f43c.png)
And the sklearn is: 
![image](https://user-images.githubusercontent.com/46867887/93946276-70d14880-fd56-11ea-9855-f8a442b05de9.png)

**Comment by YashBangera7** [comment]
Is this possible?

**Comment by azhe825** [comment]
Yes. It is possible

**Comment by prajwal2495** [comment]
This was the sklearn output
Iris-setosa	0.999993
Iris-setosa	0.999993
Iris-setosa	0.999993
Iris-setosa	0.999993
Iris-setosa	0.999993
Iris-versicolor	0.976699
Iris-versicolor	0.976699
Iris-versicolor	0.976699
Iris-versicolor	0.976699
Iris-versicolor	0.976699
Iris-virginica	0.977923
Iris-virginica	0.549697
Iris-virginica	0.977923
Iris-virginica	0.977923
Iris-virginica	0.549697
