### ISSUE TITLE
Prajwal Krishna

### ISSUE THREAD

**Issue by prajwal2495** [hil-se/fds#4]
Hey All,

I am from India living in Bengaluru right now.
Well as far as Covid situation is concerned I am sure it has become a new normal for all of us.

Amidst all this I am very excited to start this Master's journey with RIT and absolutely gutted that we can not be present in Rochester physically and have fun together. I am sure we all get to meet in Spring 2021 ( !2020 ) :D

Data science is a very new thing for me and I am sure the foundations of data science will put all of us on the right track.
Let us all collaborate together and make the most of the facilities given by RIT for remote learning.

**Comment by azhe825** [comment]
Great job opening the intro issue @prajwal2495 and welcome to DSCI-633!
