### ISSUE TITLE
Assignment 8 output is different from the expected values

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#43]
Hello Prof. Zhe and other students,

I'm getting slightly different outputs for the "iris-setosa" class but the same outputs for the remaining classes:

```python
{'Iris-setosa': {'prec': 1.0, 'recall': 1.0, 'f1': 1.0, 'auc': 1.0}, 'Iris-versicolor': {'prec': 0.8979591836734694, 'recall': 0.9777777777777777, 'f1': 0.9361702127659575, 'auc': 0.98}, 'Iris-virginica': {'prec': 0.975609756097561, 'recall': 0.8888888888888888, 'f1': 0.9302325581395349, 'auc': 0.9587654320987653}}
Average F1 scores: 
{'macro': 0.9562045824755032, 'micro': 0.9555555555555556, 'weighted': 0.9562045824755032}
```

Is there a possibility of getting different output, given that we are not introducing any randomness?

Are any others getting the same output?

Thank you

**Comment by prajwal2495** [comment]
`Confusion Matrix:
{'Iris-setosa': {'TP': 45, 'TN': 90, 'FP': 0, 'FN': 45}, 'Iris-versicolor': {'TP': 44, 'TN': 90, 'FP': 5, 'FN': 45}, 'Iris-virginica': {'TP': 40, 'TN': 90, 'FP': 1, 'FN': 45}}


Results:
{'Iris-setosa': {'prec': 1.0, 'recall': 0.49999999999944444, 'f1': 0.6666666666661728, 'auc': 0.2500000000002778}, 'Iris-versicolor': {'prec': 0.8979591836734694, 'recall': 0.4943820224713546, 'f1': 0.6376811594198278, 'auc': 0.2264931992906662}, 'Iris-virginica': {'prec': 0.975609756097561, 'recall': 0.47058823529356403, 'f1': 0.6349206349201311, 'auc': 0.25921137685871853}}

Average F1 scores: 
{'macro': 0.6468679646506282, 'micro': 0.9555555555555556, 'weighted': 1.8356958546478355}
`

Weighted average is coming wrong.
need to check on it. 
and AUC too 

i guess Prec, re-call and f1 is coming a bit right compared to expected, i guess

Best,
Prajwal

**Comment by salmassari** [comment]
> Hello Prof. and other students,
> 
> I'm getting slightly different outputs for the "iris-setosa" class but the same outputs for the remaining classes:
> 
> ```python
> {'Iris-setosa': {'prec': 1.0, 'recall': 1.0, 'f1': 1.0, 'auc': 1.0}, 'Iris-versicolor': {'prec': 0.8979591836734694, 'recall': 0.9777777777777777, 'f1': 0.9361702127659575, 'auc': 0.98}, 'Iris-virginica': {'prec': 0.975609756097561, 'recall': 0.8888888888888888, 'f1': 0.9302325581395349, 'auc': 0.9587654320987653}}
> Average F1 scores: 
> {'macro': 0.9562045824755032, 'micro': 0.9555555555555556, 'weighted': 0.9562045824755032}
> ```
> 
> Is there a possibility of getting different output, given that we are not introducing any randomness?
> 
> Are any others getting the same output?
> 
> Thank you

Did you consider calculating macro, micro and weighted in F1? If not, I think this is the reason. I have the same value once I write one formula which is from slides. For this reason, I make different equations for macro, micro and weighted in F1. As you may see my result below, F1 of Iris-setosa goes down.

`{'Iris-setosa': {'prec': 1.0, 'recall': 1.0, 'f1': 0.5, 'auc': 1.0}, 'Iris-versicolor': {'prec': 0.8979591836734694, 'recall': 0.9777777777777777, 'f1': 0.46808510638297873, 'auc': 1.020138888888889}, 'Iris-virginica': {'prec': 0.975609756097561, 'recall': 0.8888888888888888, 'f1': 0.46511627906976744, 'auc': 0.9501262626262627}}
Average F1 scores: 
{'macro': 0.9302325581395349, 'micro': 0.9567045511479035, 'weighted': 0.9555555555555555}`  



you can see the equations from this link:
https://datascience.stackexchange.com/questions/66388/what-is-the-formula-to-calculate-the-precision-recall-f-measure-with-macro-mi

**Comment by salmassari** [comment]
Professor @azhe825, I should've asked you during the class, sorry. So, Do we need to have different equations in F1 for macro, micro and weighted ? As I mentioned in my previous comment to Rigved? I just want to make sure and keep us in the right track.

**Comment by azhe825** [comment]
@salmassari 
you should be able to calculate F1 using the same equation for macro, micro, and weighted.
However, you do need to use different equations to calculate the macro, micro, and weighted recall/precision.

In another word:
F1_macro = 2 * precision_macro * recall_macro / (precision_macro+recall_macro)
And you can replace macro with micro or weighted.

**Comment by azhe825** [comment]
@salmassari 
Check your A8.py file first to see if it is up-to-date.

**Comment by azhe825** [comment]
If A8.py is up-to-date, then the only reason you are not getting correct precision for a target class is:
your confusion matrix calculation is incorrect

**Comment by azhe825** [comment]
I updated A8.py so that now you can check the predictions of the depth-2 decision tree are the same as mine.
This should be the same regardless of your implementation of my_evaluation.py

**Comment by salmassari** [comment]
@azhe825 Thank you Professor, My A8.py now is up to date. The reason of seeing my result in different way is that I am using print method for testing. Also, I was manipulating in F1 with different equations. I am using now only F1_macro = 2 * precision_macro * recall_macro / (precision_macro+recall_macro).

My result
`
{'Iris-setosa': {'prec': 1.0, 'recall': 1.0, 'f1': 1.0, 'auc': 1.0}, 'Iris-versicolor': {'prec': 0.8979591836734694, 'recall': 0.9777777777777777, 'f1': 0.9361702127659575, 'auc': 1.020138888888889}, 'Iris-virginica': {'prec': 0.975609756097561, 'recall': 0.8888888888888888, 'f1': 0.9302325581395349, 'auc': 0.9501262626262627}}
Average F1 scores: 
{'macro': 0.9567045511479035, 'micro': 0.9567045511479035, 'weighted': 0.9567045511479035}
`

**Comment by azhe825** [comment]
@salmassari I am wondering if the predictions from you sklearn decision tree are the same as mine.
If they are not, I need to reconsider how to grade your submissions.

**Comment by AbdullahA93** [comment]
Hello prof @azhe825 
I'm getting a different outputs( recall , f1) for the "iris setosa"
{'Iris-setosa': {'prec': 1.0, 'recall': 1.0, 'f1': 1.0, 'auc': 1.0},
I think the correct output should be 1.0 for both recall and f1

as the confusion matrix from (sklearn) below:

                     Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               45                0               0
Iris-versicolor            0               44               1
Iris-virginica              0                5              40

The recall for iris setosa = tp/tp+fp = 45/45+0 = 1
And the f1 for iris setosa =  2 * prec * rec / (prec + rec) = 2*1*1/(1+1) = 2/2 = 1 

"I just used sklearn ' confusion matrix to double-check my answer" 
Thank you

**Comment by salmassari** [comment]
> @salmassari I am wondering if the predictions from you sklearn decision tree are the same as mine.
> If they are not, I need to reconsider how to grade your submissions.

@azhe825 
I compared between mine and yours; they are similar.


```
clf = DecisionTreeClassifier(criterion="entropy", max_depth=2)
clf.fit(X, y)
predictions = clf.predict(X)
print(predictions)
```

output of prediction:
```
/usr/local/bin/python3.7 /Users/salmassari/DSCI-633/assignments/assignment8/A8.py
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']
```

**Comment by azhe825** [comment]
Then I think your recall calculation is incorrect— should not be 1 for setosa

**Comment by salmassari** [comment]
> Then I think your recall calculation is incorrect— should not be 1 for setosa

@azhe825 I think that once the model predicts setosa 100%, recall should be 1 and model recognizes very well. Please correct me if I am wrong.
I checked the Iris_train.csv , it's exactly same to the prediction for setosa.

If I am still wrong, I will debug mine again and do my best.

**Comment by azhe825** [comment]
@salmassari you are right. I have updated the expected output.
And the auc will always be 0<=auc<=1

**Comment by salmassari** [comment]
> @salmassari you are right. I have updated the expected output.
> And the auc will always be 0<=auc<=1

Prof. @azhe825 , thank you!

**Comment by rigved** [comment]
Thank you Prof. Zhe, @salmassari , @prajwal2495 , and @AbdullahA93 ! I'll go ahead and close out this issue.
