### ISSUE TITLE
F1 score

### ISSUE THREAD

**Issue by Krutika-05** [hil-se/fds#44]
Do we have to compute the precision and recall again as mentioned in the hint file in F1 score instead of calling it?
![fds query](https://user-images.githubusercontent.com/59906757/96020615-ec14ae80-0e6b-11eb-82e6-fba31dff738b.PNG)

**Comment by salmassari** [comment]
> Do we have to compute the precision and recall again as mentioned in the hint file in F1 score instead of calling it?
> ![fds query](https://user-images.githubusercontent.com/59906757/96020615-ec14ae80-0e6b-11eb-82e6-fba31dff738b.PNG)

@Krutika-05 No need to compute it again. You can call it again.

**Comment by Krutika-05** [comment]
That's what I thought. Thank you!

**Comment by azhe825** [comment]
@salmassari Thank you for answering it!
@Krutika-05 don't close such issues so that other students can view it.

**Comment by Krutika-05** [comment]
Okay sure Professor.
