### ISSUE TITLE
Assignment 9

### ISSUE THREAD

**Issue by salmassari** [hil-se/fds#45]
Hi Professor,

I would keep this page for all concerns in assignment 9 if you do not mind. 

One concern is that there is two declarations of a single variable of loop in mutate() which could result conflict, kindly see the code below: 
`` 
        for **i,** x in enumerate(self.generation):
            new_x = list(x)
            for **i** in range(len(x)):
`` 

" i " variable was declared two times; please let me know whether or not this would result an issue.

**Comment by azhe825** [comment]
@salmassari Thanks for pointing this out! The two "i" should definitely be different.

I have updated the hint file.

@everyone Please also update it

**Comment by salmassari** [comment]
Thank you Prof. @azhe825

**Comment by salmassari** [comment]
Hi Professor and All,

I got two iterated issues over and over. I am still not sure what they are. It seems not from my code, so I want to make sure. The issues are below: 

``    clf = self.model(*decision)
TypeError: type object argument after * must be an iterable, not int   ``

The second one
`
    predictions = clf.predict(X_test)
  File "../assignment2/my_DT_hint.py", line 114, in predict
    if type(self.tree[node])==Counter:
KeyError: 2
`

Could anyone confirm whether the assignment is done or not? This helps me to know if the issue is from my code or not.

**Comment by azhe825** [comment]
A useful way for debugging is to add a try and except to catch the error:
```
try:
  clf = self.model(*decision)
except:
  set_trace()
```

**Comment by salmassari** [comment]
> A useful way for debugging is to add a try and except to catch the error:
> 
> ```
> try:
>   clf = self.model(*decision)
> except:
>   set_trace()
> ```

This is what I get
```
> /Users/XX/DSCI-633/assignments/assignment9/test.py(73)evaluate()
-> indices = [i for i in range(len(self.data_y))]
(Pdb) 
```

**Comment by azhe825** [comment]
Then you can debug what happened. E.g. check what decision is

**Comment by AbdullahA93** [comment]
@salmassari @azhe825
I get the same issue with my_DT file ( in predict if type(self.tree[node])==Counter).
I have used the TA's assignment 2 code but still the same error.

If anyone else has the same error please let us know?

**Comment by pari0805** [comment]
Yes, I'm also having the same problem

**Comment by azhe825** [comment]
I found that the TA's reference answer to my_DT.py was not updated. It did not convert the node to leaf node when max_depth was reached.

It has been fixed now. Please update.
https://github.com/ketakisbarde/DSCI-633/blob/master/assignments/assignment2/my_DT.py

**Comment by salmassari** [comment]
> I found that the TA's reference answer to my_DT.py was not updated. It did not convert the node to leaf node when max_depth was reached.
> 
> It has been fixed now. Please update.
> https://github.com/ketakisbarde/DSCI-633/blob/master/assignments/assignment2/my_DT.py

@azhe825 Thanks Professor, it works well now.

**Comment by salmassari** [comment]
Hi Professor, @azhe825 

I am tending to use TA's solution in assignment 2, so do I need to update my assignment 2 ? and replace my solution with TA's solution?

**Comment by azhe825** [comment]
Yes. You can do that.

**Comment by YashBangera7** [comment]
Sir, do we need to change it in our repo too?

**Comment by azhe825** [comment]
You can choose whether to use the reference answer to finish A9. If you choose so, you need to overwrite your repo with the reference answer
