### ISSUE TITLE
Infinite loop in assignment 9 tune method

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#48]
Hello Prof. Zhe,

I'm running into an infinite loop in the tune() method.

```python
while self.life > 0 or self.iter < self.max_generation:
    self.select()
    if self.compete(self.pf, self.pf_best):
        self.life = self.max_life
    else:
        self.life -= 1
```

Here, `self.compete` always returns `True` for me with the default values passed to `my_GA`, so `self.life` is never decremented. The following change in the `while` loop condition fixes it for me:

```python
while self.life > 0 and self.iter < self.max_generation:
```

Changing `or` to `and` ensures that the loop breaks if `self.life` is less than 1 or if `self.iter` crosses the `self.max_generation` limit.

Please let me know if this is correct.

Thank you

**Comment by azhe825** [comment]
1. That probably means your compete function is incorrect.

2. But yes, it should be and instead of or

**Comment by rigved** [comment]
Thank you Prof. Zhe. I'll recheck my `compete` method.
