### ISSUE TITLE
Assignment 9: k-fold cross-validation

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#49]
Hello Prof. Zhe,

In assignment 9, we are using the `k`-fold cross-validation technique to find the average metrics over `k`-subsets. So, I feel we should average over the number of folds (`k` in this case) instead of the number of data points.

Current code:

```python
objs_crossval = objs_crossval / float(len(self.data_y))
```

My suggestion:

```python
objs_crossval = objs_crossval / float(self.crossval_fold)
```

This change will cause the metrics taken from 2-folds (default value passed to `my_GA`) to be averaged correctly.

Please let me know if this change is correct.

Thank you

**Comment by azhe825** [comment]
You are supposed to average the obj even when the sub folds were not divided equally. Take this into consideration and find the correct solution when you sum the objs.

**Comment by rigved** [comment]
Understood. Let me check again on that.

**Comment by rigved** [comment]
Thank you Prof. Zhe. I have now performed a weighted average instead of assuming that the length of each fold is uniform.
