### ISSUE TITLE
Mayuresh Nene

### ISSUE THREAD

**Issue by Mayuresh-12** [hil-se/fds#5]
Hi,
 
I am from Pune, India. Glad I will be starting this program this week, as it's been on my radar for a year now. This was mainly because I participated in an idea at a Hackathon at my internship. That sparked my interest in diving deeper into the field. 

This has definitely been a roller coaster year for the most part and I am sure this new phase will bring a lot of interesting new experiences for us all! Can't wait to learn and have fun at the same time :)

**Comment by azhe825** [comment]
Great job opening the intro issue @Mayuresh-12 and welcome to DSCI-633!
