### ISSUE TITLE
Duplicate data points showing up in pf_best in assignment 9

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#51]
Hello Prof. Zhe,

Sometimes when I run `A9.py`, I get duplicate data points in `pf_best`, as mentioned by another student during the lecture today. The result of that is I get duplicate precision and recall values as shown below:

```python
[array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597]), array([0.95041809, 0.96006597])]
[0.96479161]
```

If we check for duplicate points before adding into `pf_best`, this doesn't occur.

Origninal code:

```python
if not_dominated:
    to_add.append(j)
    modified = True
```

Suggestion:

```python
if not_dominated and pf_new[j] not in pf_best:
    to_add.append(j)
    modified = True
```

Does this suggestion look good?

Thank you

**Comment by azhe825** [comment]
If you do this:
```
forall y in pf_best; self.is_better(y, x) == -1
```
The duplicate points should not be added into pf_best since
is_better(a,b) returns 0 if a==b

**Comment by rigved** [comment]
Thank you Prof. Zhe. I had misinterpreted that entire comment:

```python
# If one point x in pf_new is not dominated by any point y in pf_best (and does not exist in pf_best)
# (forall y in pf_best; self.is_better(y, x) == -1)
# add that point x to pf_best
```

Only when x is not dominated by even a single y, then we should add x to pf_best.
