### ISSUE TITLE
Assignment#9 checking the output

### ISSUE THREAD

**Issue by ra9118** [hil-se/fds#53]
Hi Professor and students. I am getting this output: C:\Users\rana8\miniconda3\python.exe C:/Users/rana8/OneDrive/Desktop/Assignments/DSCI-633/assignments/assignment9/A9.py
[(0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665), (0.9733333333333332, 0.9166666666666665)]
(0.974202308214528, 0.918755939470286)
can you please let me know if I am correct or no?

**Comment by rigved** [comment]
Hi,

Each output value may differ due to randomness but I think the last line should be a single F1 score instead of a tuple.

Thanks

**Comment by ra9118** [comment]
Thank you Rigved

**Comment by azhe825** [comment]
@ra9118 I think you have duplicate outputs. That should not happen.
