### ISSUE TITLE
Output value 

### ISSUE THREAD

**Issue by pari0805** [hil-se/fds#54]
Hello Professor and Everyone 
I'm getting the following answer when I'm trying to run the model and they are random each time is this output correct?

[array([0.66666667, 0.49997257]), array([0.66666667, 0.5       ]), array([0.93964592, 0.93964592]), array([0.94797531, 0.94803177]), array([0.79732435, 0.71325817]), array([0.94129137, 0.94078368]), array([0.92491124, 0.92491124]), array([0.33333333, 0.11111111]), array([0.94183728, 0.94395821]), array([0.94983834, 0.95288066])]
[0.96389713]

**Comment by ra9118** [comment]
To get same professor output, i think, we need to update evaluate  function to use `self.crossval_fold` instead `len(self.data_y)` in this line

```
               predictions = clf.predict(X_test)
                pred_proba = clf.predict_proba(X_test)
                actuals = y_test
                objs = np.array(self.obj_func(predictions, actuals, pred_proba))
                if type(objs_crossval) == type(None):
                    objs_crossval = objs
                else:
                    objs_crossval += objs

            objs_crossval = objs_crossval / float(self.crossval_fold)
```

The reason since we are accumulating  measurement matrix in the `objs_crossval` base on number of folds.
So we need to divide then by number times to get average.
This what i think


output example
```
[array([0.95481602, 0.95650585])]
[0.96184688]
```

**Comment by ra9118** [comment]
I may not be correct

**Comment by pari0805** [comment]
I'm getting really different values when I did that though

**Comment by azhe825** [comment]
@pari0805 your output is definitely not correct

**Comment by azhe825** [comment]
@ra9118 you can do that. But you don’t have to.
