### ISSUE TITLE
Using nltk library in project

### ISSUE THREAD

**Issue by ra9118** [hil-se/fds#55]
Hello Professor,
Can we use nltk library in project? i know we limited  on which libraries we can use in project.
The reason i am asking about this library, because it  has hug dataset for Lemmatization almost all words, also list of stop words etc.
It would give better clean up for text than we write the per-processing manually
Thanks,

**Comment by azhe825** [comment]
No.

**Comment by ra9118** [comment]
ok.

**Comment by azhe825** [comment]
I don’t want you to spend too much effort on data preprocessing. So sklearn would be enough.

**Comment by ra9118** [comment]
Thank you professor.

**Comment by prajwal2495** [comment]
Hi @ra9118 ,

Since genism can be used, you can make use of STOPWORDS and remove_stopwords from gensim.parsing.preprocessing which works similar to nltk and I believe Lemmatization is also available in genism with similar implementation to nltk.

**Comment by ra9118** [comment]
@prajwal2495  that makes sense. Thanks  will try it

**Comment by Y-Singh** [comment]
@azhe825 Professor, since we can use gensim, can we also use 'Pattern'? The Lemmatization for gensim requires the Pattern library and I wasn't sure if we could use it or not.

**Comment by azhe825** [comment]
@Y-Singh if that requires additional installation, no you cannot. The TA will execute your code without installing any addition library.

**Comment by Y-Singh** [comment]
@azhe825 Thank you for the clarification Professor. It does so I will ignore it

**Comment by ra9118** [comment]
@ Y-Singh  you donot need to install Pattern, it compatibility bug between genism  and python version that you use. Pattern is already get installed when you install genism.
I have this issue  and fix it by using the current settings
Python 3.6
genism 3.8.3
 works fine.

**Comment by Y-Singh** [comment]
@ra9118 So I went ahead and made a new Python 3.6 env and I installed gensim but it didn't install Pattern itself. I keep getting an import error
![image](https://user-images.githubusercontent.com/47701821/99326270-fd275580-2845-11eb-8419-d569cf25856e.png)

**Comment by ra9118** [comment]
can you try "`pip install Pattern`" i know the professor donot want external library but here i think it needed as part of genism , In your code you donot call Pattern library methods instead you calling genism  library methods that calls Pattern.

This what i think you have in code
`from gensim.utils import lemmatize`

if that you arenot calling another library  you calling only gensim

**Comment by ra9118** [comment]
@Y-Singh 
This approve what i am saying from gensim source code

https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L312

It configuration issue with if MYSQL isnot in machine  and i search online it been seen alot

**Comment by Y-Singh** [comment]
@ra9118 So after looking at the repo that you posted and searching around, the lemmatization in gensim is the only function that uses the "Pattern" library, which is why it's an optional dependency for gensim and why installing gensim does not automatically install "Pattern". 
@azhe825 Do you happen to know of any other way to perform any lemmatization since to do so with gensim, it needs "Pattern"?

**Comment by azhe825** [comment]
@Y-Singh sklearn should have similar functionality, at least it has everything this project needs.

**Comment by rigved** [comment]
Also, lemmatization is a fancier version of stemming. You should still be able to use stemming from `gensim` without including any external libraries.
