### ISSUE TITLE
Changes to the skeleton code in project.py

### ISSUE THREAD

**Issue by prajwal2495** [hil-se/fds#56]
Hello Professor @azhe825 

I wanted to know whether it is fine to make little changes to the `if __name__ == "__main__":` block of code to our comfort.
Changes could be 
1. call to fit method of my_model class
2. extracting X and y variables in a different method. etc.,

Will make sure that it doesn't affect the functionality.

Thanks,
Prajwal

**Comment by azhe825** [comment]
@prajwal2495 
1. Yes. You can change code under `if __name__ == "__main__":`
2. You cannot change the code structure of the class since we will assume that structure when grading.

**Comment by prajwal2495** [comment]
okay, Thanks Professor

**Comment by salmassari** [comment]
Hi Professor @azhe825 ,
Since the code structure is very important, I would like to see whether or not mine is well-structured if you do not mind. I split the dataset into two files to satisfy the requirement of the structure. My code structure is below: 

```
if __name__ == "__main__":
    start = time.time()
    # Load training data
    train = pd.read_csv("../data/job_train1.csv")
    # Replace missing values with empty strings
    train_data = train.fillna("")
    y_train = train_data["fraudulent"]
    X_train = train_data.drop(['fraudulent'], axis=1)
    # Load testing data
    test = pd.read_csv("../data/job_train2.csv")
    test_data = test.fillna("")
    y_test = test_data["fraudulent"]
    X_test = test_data.drop(['fraudulent'], axis=1)
    # Train model
    model = my_model()
    model.fit(X_train,y_train)
    runtime = (time.time() - start) / 60.0
   predection= model.predict(X_test)
```

**Comment by azhe825** [comment]
I do not see any problem. For changing the skeleton:

1. You can do whatever you want in the main function.

2. Beware that you should not put any functionality in the main function (e.g. the preprocessing) since when your code is getting graded, it won’t use your main function.

**Comment by salmassari** [comment]
Sure, thank you professor.
