### ISSUE TITLE
Classification report after data balancing.

### ISSUE THREAD

**Issue by Mayuresh-12** [hil-se/fds#57]
Hi @azhe825 ,

<img width="475" alt="Screenshot" src="https://user-images.githubusercontent.com/68107756/98771811-44a77f00-240b-11eb-9dfd-c2daa34e0a11.png">

Fraudulent == 0 had 8400+ values initially and Fraudulent == 1 was around 450. This created an imbalance problem, which generated an accuracy score of 96%. 

I performed undersampling on Fraudulent == 0 down to around 450 values . I fitted this to a decision tree classifier and I've attached the classification report. Could you please review and let me know if this is on the right track? Thanks!

**Comment by azhe825** [comment]
I think you are on the right track. As you have found out, accuracy means nothing due to the imbalanced data. Keep trying to improve the f1 score on fraudulent = 1 class.

**Comment by Mayuresh-12** [comment]
Thank you Professor!
