### ISSUE TITLE
Problem with np.nan values remaining after using fillna()

### ISSUE THREAD

**Issue by Rainmaker519** [hil-se/fds#58]
Currently my model trains on randomly sampled data which contains np.nan values. I am using data.fillna("") in order to replace them before I pass the data to my test() method, but I still get an error reading  

> ValueError: np.nan is an invalid document, expected byte or unicode string.

whenever it reaches my preprocessing. Am I missing something or misunderstanding what the fillna() method does? Any help would be appreciated.

![capnpnan](https://user-images.githubusercontent.com/13624733/99156063-066cc280-268c-11eb-9172-c0d5592c7aa5.JPG)

**Comment by azhe825** [comment]
@Rainmaker519 i think fillna() should work. Please make sure you pulled the latest version of the repo and see if running the project.py file gives you the same error

**Comment by Y-Singh** [comment]
I believe that when using .fillna(), you have to set the dataframe equal to itself. So try replacing that line with ...
`data = data.fillna("")`

**Comment by Rainmaker519** [comment]
@Y-Singh That was it, thanks!

**Comment by azhe825** [comment]
@Y-Singh great! Thx for the help!
