### ISSUE TITLE
How project is graded

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#59]
I find quite many students confusing about how your project.py file is utilized in grading. To make it clearer, I separated the project.py file and created a [test.py](https://github.com/hil-se/fds/blob/master/assignments/project/test.py) file. DO NOT change the test.py file.

The principle is:
You can do anything in your project.py file as long as:
 - on a machine that only installed scikit-learn, pandas, and gensim,
 - when you execute the test.py file, it correctly outputs the f1 score.

**Comment by neha6351** [comment]
Do we need to use assignment8? Can't we use sklearn.metrics.f1_score?

**Comment by Krutika-05** [comment]
We have already used the earlier project.py. Now the recent commits on the project in github repo suggests some changes which would be difficult to incorporate as the we have been using the earlier files for the past month.
Please address this concern.

**Comment by azhe825** [comment]
@neha6351 you can use any evaluation. However, when your file is getting graded, I will use the reference answer version of my_evaluation to calculate your f1 score.

**Comment by azhe825** [comment]
@Krutika-05 If you find your project.py file not compatible with the test.py file, that means your initial understanding is incorrect. The requirement of the project has not changed since the beginning. The test.py file only serves to let you whether your submission will be graded correctly before you submit your file.

**Comment by azhe825** [comment]
Again, there is no change to the project. If you correctly implemented the project.py file, you should find it no difference when running with test.py file.
