### ISSUE TITLE
Rigved Rakshit

### ISSUE THREAD

**Issue by rigved** [hil-se/fds#6]
Hello,

I'm from Mumbai, India. I was a System Architect at my previous company. I have been interested in Data Science (and Natural Language Processing specifically) for a few years now and I'm absolutely delighted to start my Data Science journey with this course! COVID-19 has wreaked havoc throughout the world but everyone is learning to mitigate its spread. I hope to meet everyone soon in-person!

Rigved

**Comment by azhe825** [comment]
Welcome @rigved! Stay healthy in this pandemic!
