### ISSUE TITLE
Spencer Argenna intro

### ISSUE THREAD

**Issue by sma4396** [hil-se/fds#63]
My name is Spencer. I am a Mechanical Engineer who works at Lockheed Martin, primarily working with aircraft data. I live in Rochester, and am currently working from home. With the extra time on my hands due to the pandemic, I decided learning about data science was worth investing in, so I started my Masters Degree online. After graduation I'll probably keep working at Lockheed but hope to teach sometime in the future.

**Comment by azhe825** [comment]
@sma4396 Welcome to the online MS program!
