### ISSUE TITLE
Heather Akers-Healy intro

### ISSUE THREAD

**Issue by abbynormative** [hil-se/fds#65]
Hi there! I live in San Francisco and have just a few classes left in the online Masters. After graduation I plan on applying to data science or analyst jobs in the Bay Area or remote. The pandemic has had a pretty big impact on my social and family life, but I'm hoping that this year will gradually be better as more people get vaccinated. 

Look forward to this class!

**Comment by azhe825** [comment]
@abbynormative I also hope life will get better soon and good luck on your job hunting!
