### ISSUE TITLE
Nick John Intro

### ISSUE THREAD

**Issue by nicholas-john** [hil-se/fds#66]
Hey, I'm Nick. I grew up about two hours from RIT in Ithaca, NY. I did my undergrad at RIT, and now I'm continuing with a masters in applied and computational mathematics. I enjoy grocery shopping, and I don't enjoy mornings. Covid has been tough, but luckily my family members have all stayed safe. After graduation I want to work in industry doing something constructive and good, and of course I want to do awesome things with math and data science. I'm grateful to be able to take this course, and I look forward to learning with and from all of you.

**Comment by azhe825** [comment]
Welcome to the class @Ndj3315!
