### ISSUE TITLE
Isabela Introduction

### ISSUE THREAD

**Issue by ghost** [hil-se/fds#68]
Hello everyone! 

My name is Isabela. I am a Masters student in the Data Science program. I began learning a bit about Data Science while taking stochastic processes at RIT during my undergrad and absolutely loved it. I did my Bachelors is Electrical Engineering and am hoping to use my domain knowledge in a Data Science role in the future. 
I am from NYC and the pandemic hit me and my family pretty hard, but I try to stay optimistic. Now, I am back at RIT to take my classes and am aiming to graduate next spring.
Aside from academics, I love to play guitar and am a huge FC Barcelona fan.

**Comment by azhe825** [comment]
@ixc9907 wish you find your dream job before graduating!
