### ISSUE TITLE
Ashish Intro

### ISSUE THREAD

**Issue by ashishgalagali** [hil-se/fds#69]
Hello everyone, 
My name is Ashish Galagali. I am from India, currently staying in Rochester. I am pursuing my Masters in Software Engineering. I feel sad that due to the pandemic, we missed out on the in-person classroom experience and college activities. Thanks to technology which has been a great help in sustaining the activities around the world and keeping people connected. I would like to contribute to such innovations that would help the masses after graduation. Looking forward to the classes and hoping the situation gets better and we could meet in-person by the end of this semester 🤞

**Comment by azhe825** [comment]
@ashishgalagali I also feel sorry for not being able to provide in-person lectures. Hope the next semester will get better!
