### ISSUE TITLE
Dave Putz here.

### ISSUE THREAD

**Issue by djpnce** [hil-se/fds#70]
Hi everyone.

My name is Dave Putz. I currently work in the Marketing department at RIT/NTID, under NTID. I graduated RIT in 2015 with a bachelors of science in Economics. I have little programming experience but I took a Python course over the summer to help prepare for my graduate studies in Data Science.

I'm excited to learn more from everyone.

**Comment by azhe825** [comment]
Nice to meet you @djpnce! You will surely have more programming experience through this course.
