### ISSUE TITLE
Dylan Chase Intro

### ISSUE THREAD

**Issue by dychase99** [hil-se/fds#71]
Hello! My name is Dylan Chase and I am a BS/MS student in applied and computation mathematics. After school, I plan to put my degree to good use and become an actuary. I grew up in Cherry Creek, NY, which is around two hours southwest of here. Outside of school, I enjoy sports, mostly basketball and soccer, and I also enjoy playing a lot of video games. Looking forward to a great semester!

**Comment by azhe825** [comment]
Looking forward to a great semester!
