### ISSUE TITLE
Ian Effendi intro

### ISSUE THREAD

**Issue by effendiian** [hil-se/fds#72]
Hi all, I'm Ian Effendi. I'm starting my master's in Data Science and am excited to see where the program will go. I'll be joining this course from my home in the Bronx. I graduated last May from RIT with a degree in Game Design & Development and spent the last nine months making educational math games for kids with a small start-up in NYC.

My family has been impacted by the pandemic but we're making it work one day at a time. I hope to apply the skills I learn during this program to a career in data analysis for video game studios. Outside of RIT, I'm also a professional tax preparer, working at a firm that serves low-income clients in NYC to help file federal and state taxes.

If you utilize RIT's Writing Commons services (which are remote this year), you'll also see me on staff as a part-time Graduate Writing Consultant. It's my pleasure to meet you all (virtually)!

**Comment by azhe825** [comment]
Nice to meet you @rimij405! I am a big fan of video games so please make good ones :)
