### ISSUE TITLE
Reference answer to the assignments

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#80]
Answers will be available at https://github.com/hil-se/ans_fds

**Comment by Goitsemedi888** [comment]
[image: image.png]

I updated the google docs a week ago not sure why its not updated on your
end

**Comment by Goitsemedi888** [comment]
[image: image.png]

**Comment by azhe825** [comment]
@Goitsemedi888 I do not know what you mean and I cannot see your image.

**Comment by azhe825** [comment]
Reference answer to Assignment 3 is available at https://github.com/hil-se/ans_fds

**Comment by Goitsemedi888** [comment]
stats = Counter(labels)
    N = float(len(labels))

    if self.criterion == "gini":  # Implement gini impurity
        impurity = (1-np.sum(N)**2).sum(axis=1)
    elif self.criterion == "entropy":  # Implement entropy impurity
        impurity = np.sum([(N/np.sum(N)).sum(axis=1) *
np.log2(N/np.sum(N).sum(axis=1))])
    else:
        raise Exception("Unknown criterion.")
print(impurity)
#return impurity

I do not get error message but nothing prints...i need assist

**Comment by azhe825** [comment]
@Goitsemedi888 
You can use set_trace() to debug which line you can get to.

**Comment by Goitsemedi888** [comment]
set_trace does not work in pycharm... is there a tutor you can recommend?.
I am over getting zeros and spending countless hours on youtube for a class
costing me $3000+ to learn absolutely nothing ...ISTE 600 goes over the
same things and demo's the software. I did work with the T.A and its
typically brief i understand he has his own projects and other students to
assist.

**Comment by nairnish** [comment]
You can use pdb.set_trace() in pycharm to do the same. Hope this helps.

**Comment by Goitsemedi888** [comment]
I need a tutor for this course. I have done w-3 schools and demo python to
get basics and I can do headers, remove columns, do replacement but thats
not cutting reconstructing sklearn using python and the half a lecture we
did on python does not match up in complexity of assignments ... i have 3
zeros for $3000. I have tried to get help, every other class demos the code
walks through logic ...you cannot teach calculus with words, same applies
here...the assignment answers do not break down the logic of the algorithm
so i spent more hour highlighting and googling each function.

**Comment by azhe825** [comment]
I think there are two tutors available for this course. They are listed as support staffs in the mycourses system. You can reach out to them for help.

**Comment by Goitsemedi888** [comment]
my sincerest apologies, i had no intent to be rude. my work schedule
coincides with class and help hours. I had to drop session when my boss
appeared.

**Comment by azhe825** [comment]
No worries.
