### ISSUE TITLE
Please enter your time zone information

### ISSUE THREAD

**Issue by azhe825** [hil-se/fds#81]
Please enter your time zone information in the [google sheet](https://docs.google.com/spreadsheets/d/1Kyuqa3Seh_noWsjBam3bHcfzmbwp7eWhAr-Qw4eCkqI/edit?usp=sharing).

**Comment by Goitsemedi888** [comment]
[image: image.png]
it's not throwing errors but it's also not doing anything... I am at wits
end what is wrong with this

**Comment by azhe825** [comment]
@Goitsemedi888 please create a new issue for your questions. And I cannot see your image.

**Comment by Goitsemedi888** [comment]
I have a neurotic level of obsession with python and i am starting to make
synapse but, i do need help with the logic as there are many ways to do
these things
 i am stuck on the for loop to itterows how to form that statement. x is
test data and self.X is training. also i realize we have 3 classes and 4
measures ... my actual brain is now in a loop

def dist(self,x):
    # Calculate distances of training data to a single input data
point (distances from self.X to x)
    # Output np.array([distances to x])
    for value x in Key[value]
        for x in X
    if self.metric == "minkowski":
        distances = np.sum((abs((x-self.X) ** self.p)) ** (1 / self.p))

    elif self.metric == "euclidean":
        distances = np.sqrt(np.sum(x-self.X)**2)

    elif self.metric == "manhattan":
        distances = np.sum(abs(x-self.X))

    elif self.metric == "cosine":
        distances = np.dot(x, self.X) / (np.sqrt(np.dot(x, x)) *
np.sqrt(np.dot(self.X, self.X)))

    else:
        raise Exception("Unknown criterion.")
    return distances

**Comment by traversingtrav** [comment]
Phrase like you ask the question for every test x for every train x for every class column calculate distance save in list sort the list for smallest k resultsSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Goitsemedi888 <notifications@github.com> Date: 2/20/21  1:56 PM  (GMT-05:00) To: hil-se/fds <fds@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [hil-se/fds] Please enter your time zone information (#81) 

I have a neurotic level of obsession with python and i am starting to make

synapse but, i do need help with the logic as there are many ways to do

these things

 i am stuck on the for loop to itterows how to form that statement. x is

test data and self.X is training. also i realize we have 3 classes and 4

measures ... my actual brain is now in a loop



def dist(self,x):

    # Calculate distances of training data to a single input data

point (distances from self.X to x)

    # Output np.array([distances to x])

    for value x in Key[value]

        for x in X

    if self.metric == "minkowski":

        distances = np.sum((abs((x-self.X) ** self.p)) ** (1 / self.p))



    elif self.metric == "euclidean":

        distances = np.sqrt(np.sum(x-self.X)**2)



    elif self.metric == "manhattan":

        distances = np.sum(abs(x-self.X))



    elif self.metric == "cosine":

        distances = np.dot(x, self.X) / (np.sqrt(np.dot(x, x)) *

np.sqrt(np.dot(self.X, self.X)))



    else:

        raise Exception("Unknown criterion.")

    return distances

**Comment by azhe825** [comment]
@Goitsemedi888 
x is a single test data point while self.X is a pd.DataFrame which contains all the training data points.

you need to calculate the distances from each data point in self.X to x.
