### ISSUE TITLE
Assignment 4 output probability question

### ISSUE THREAD

**Issue by alanahough** [hil-se/fds#83]
I was just curious if anyone else finished implementing the decision tree but got the last 5 predictions as Iris-virginica with 0.975610 probability.  This is what's happening to me, and I can't figure out what's wrong.  I did some digging and the reason mine doesn't have a probability of 1 is because the leaf node that all those observations go to has a count of 40 for virginica and 1 for versicolor.  It doesn't split after this node because best_feature and (current_impure - best_feature[1]) are not greater than self.min_impurity_decrease * N.  I'm pretty sure I implemented the impurity function and find_best_split function from the hint file correctly, so I'm not sure where to go from here.

**Comment by azhe825** [comment]
@alanahough the default min_impurity_decrease = 0 so you should not have that problem when running A4.py.

**Comment by alanahough** [comment]
The min_impurity_decrease = 0 but (current_impure - best_feature[1]) for that node is -0.0027, so it makes it a leaf node.  Can you confirm that my weighted impurity equations in the best feature functions are correct?  That's the only thing I can think of that would be causing this.  They are: 
`left_impurity = N_left / N * self.impurity(left_labels)

 right_impurity = N_right / N * self.impurity(right_labels)

 split_impurity = left_impurity + right_impurity`

**Comment by azhe825** [comment]
1. The equation is correct but there is no way that after the split impurity increases (could be the same though so maybe it is caused by the float variables?).
2. If you read the fit() function in the hint file carefully, you will notice that you should not divide by N when calculating the impurities.

**Comment by alanahough** [comment]
Ah yeah, the dividing by N in the left and right impurities was my issue.  I misinterpreted some of what was going on in the fit() function.  Thanks for the help!
