### ISSUE TITLE
assignment 4 splitting continuous data more than once.  

### ISSUE THREAD

**Issue by traversingtrav** [hil-se/fds#84]
In lecture the example discussed showed splitting the continuous data once as less than a single value and greater than a single value. But should we be writing are code for splitting each column N times. I'm a little confused how to upscale more than one split on continuous data.

**Comment by azhe825** [comment]
It is possible that one column can be split multiple times in a decision tree. Take this as an example:

Node 0: (x: 1 - 100) 
Node 1: (x: 1 - 50), Node 2: (x: 51 - 100)
Node 3: (x: 1 - 25), Node 4: (x: 26 - 50)

The point is, when you split Node 1 into Node 3 and 4, you will not see any data points with x > 50, so it is the same strategy as splitting Node 0 into Node 1 and 2.

**Comment by traversingtrav** [comment]
I was more thinking of the income data instead of calculating the best split at an individual point say <100k what if the best split is less than 100k and great than 160K

**Comment by traversingtrav** [comment]
or if we have 3 y results yA split less than 100k yB split less than 160k and yC split greater than 160k

**Comment by azhe825** [comment]
@traversingtrav we always do a binary split.
