### ISSUE TITLE
Assignment Grade Changing

### ISSUE THREAD

**Issue by traversingtrav** [hil-se/fds#85]
Is there a reason why previously posted grades changed?

**Comment by azhe825** [comment]
Sometimes the grades were not generated correctly. @traversingtrav Which grade are you referring to specifically?

**Comment by traversingtrav** [comment]
All of my last three assignments changed but specifically my assignment 2
went from 4 to 0. I did notice when I loaded my assignment 3 I accidentally
updated assignment 2 to an empty copy.  I did not fix it because it had
already been graded but I will repost my original submission.

**Comment by azhe825** [comment]
Yes. This is possible as I updated the grading function last week and re-graded A2. I will change your A2 grade back to 4

**Comment by azhe825** [comment]
@traversingtrav if you upload your original A2 submission, you might even receive a slightly higher score based on the new grading function.
