### ISSUE TITLE
Sanket Waghmare

### ISSUE THREAD

**Issue by sam2396** [hil-se/fds#9]
Hello all,
I am from Mumbai,India.
The amount of Information that can be collected, analysed and acquired from data is something that has always fascinated me.
I'm so glad that I am going into a field that I am passionate about and excited to see how RIT helps me in delving deeper into it.
COVID-19 has definitely been an obstacle that we have been surviving through, but connecting and working together, we can make this semester worthwhile.
See you all soon.

**Comment by azhe825** [comment]
Welcome @sam2396! See you soon!
