### ISSUE TITLE
Assignment 8 macro F1 score

### ISSUE THREAD

**Issue by abbynormative** [hil-se/fds#90]
Hi Professor, I'm puzzled about the macro F1 in the expected results. The macro score will just be the average of the F1 scores, correct? Taking the average of 0.9302325581395349 + 0.9361702127659575 + 1 gives me 0.9554675903018307, not 0.9567045511479035 as shown.

**Comment by azhe825** [comment]
The following is NOT correct:

Any averaged F1 score is calculated by 2\*prec\*rec/(prec+rec)

That means, instead of calculating the F1 score for each class first then do an average (like what happens when you calculate averaged precision or recall), you should calculate the averaged precision and averaged recall first and use those two to calculate averaged F1.

**Comment by abbynormative** [comment]
Got it, thank you.

**Comment by azhe825** [comment]
@abbynormative and everyone else:
I have checked scikit-learn and wiki, we should calculate the averaged F1 scores by calculating the F1 scores on each class first, then do the average. 

DO NOT calculate the averaged precision and recalls then use those to calculate the F1 score. I have also updated the hint file and the assignment description for this purpose.

**Comment by sma4396** [comment]
I'm very confused by this. If we are to calculate the F1 scores on each class first, then do an average, no matter what our average f1 score will be the same for all three methods (macro, micro, weighted). Am I missing something here?

**Comment by azhe825** [comment]
@sma4396 there are three different ways to average the metrics (when we say average, we do not mean just take a mean). Check the slides for more details.

**Comment by abbynormative** [comment]
I'm getting a slightly different value for the weighted F1 score vs the macro, but the expected answer has them as the same value. Is it correct they would be the same?

**Comment by azhe825** [comment]
For that data, they should be the same.
