### ISSUE TITLE
Assignment #2

### ISSUE THREAD

**Issue by sma4396** [hil-se/fds#91]
Where can we get corrections to previous assignments. I got a 6.5/7 for assignment 2 but am going to need to utilize for assignment 9.

**Comment by sma4396** [comment]
Correction. It is assignment 4 that needs to be utilized. I believe I found my error and fixed it. Did you mention we could get partial credit back on these assignments if we fixed the issues for a better score?

**Comment by azhe825** [comment]
@sma4396 i will get to that in our next lecture.
