### ISSUE TITLE
assignment 8 reference answer bug?

### ISSUE THREAD

**Issue by abbynormative** [hil-se/fds#95]
I think there may be a small bug in the reference answer for assignment 8? I'm getting a divided by zero error from the f1 function when I run my assignment 9 code that is otherwise working. In the outer else block of f1, if I set f1 = 2.0 * prec * rec / (prec + rec + 1e-5), my code for assignment 9 will run.

**Comment by azhe825** [comment]
@abbynormative you are absolutely right. Will update the reference answer tomorrow.

**Comment by azhe825** [comment]
And the good news is that you will receive 1 extra credit for finding this bug :)

**Comment by azhe825** [comment]
Fixed
